version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker

  # api:
  #   container_name: api-container
  #   image: node:18
  #   working_dir: /usr/src/auth-api
  #   restart: always
  #   environment:
  #     - MONGO_URL=mongodb://docker:docker@mongo:27017/?authMechanism=DEFAULT
  #     - PORT=10000
  #   command: bash -c "npm install --omit=dev && npm run start"
  #   volumes:
  #     - ./dist/:/usr/src/auth-api/dist/
  #     - ./package.json:/usr/src/auth-api/package.json
  #   ports:
  #     - "10000:10000"
  #   links:
  #     - mongo