version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker

  api:
    container_name: api-container
    build: .
    image: auth-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/auth-api/dist
      - ./package.json:/usr/src/auth-api/package.json
    ports:
      - "10000:10000"
      - "10500:10500"
    links:
      - mongo