version: '3'

services:
  clean-api-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: